--- fs/Makefile
+++ fs/Makefile
@@ -126,3 +126,4 @@
 obj-$(CONFIG_GFS2_FS)           += gfs2/
 obj-$(CONFIG_EXOFS_FS)          += exofs/
 obj-$(CONFIG_CEPH_FS)		+= ceph/
+obj-$(CONFIG_AUFS_FS)           += aufs/
